// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import NotificationSettingController from "./notification_setting_controller"
application.register("notification-setting", NotificationSettingController)

import PushNotificationController from "./push_notification_controller"
application.register("push-notification", PushNotificationController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
